--- 
- name: install and enable nginx
  hosts: all
  tasks: 
    - name: install nginx
      package:
        name: nginx
        state: present 
    - name: enable and start nginx
      service: 
        name: nginx
        enabled: yes
        state: started
...
